= Welcome to {lab_name}!

[%hardbreaks]

== はじめに

今日のダイナミックなIT環境において、組織はクラウドネイティブ・イノベーションの要求と並行して、従来の仮想化管理の複雑さに取り組んでいます。このワークショップでは、Red Hat OpenShift VirtualizationをAnsible Automation PlatformおよびRed Hat Advanced Cluster Management for Kubernetesと組み合わせることで、仮想ベースかコンテナベースかを問わず、あらゆるワークロードに対応する統合型、効率的、かつ安全なプラットフォームを実現する方法を示し、ITプロフェッショナルが自信を持ってこのハイブリッドな現実に対応できるよう支援します。

このラボは、大変好評を博した https://www.redhat.com/en/events/na-red-hat-openshift-virtualization[Experience OpenShift Virtualization Roadshow^] ラボの続編であり、環境を管理し、導入以降に仮想マシン管理者に求められる重要な運用タスクを実行するための知識とツールを提供します。これにより、仮想化されたワークロードは、初期導入後も長期間にわたって効率的に管理・保守されます。

== ラボ環境の要件

* 参加者は、Webブラウザとインターネット接続を備えたパソコンをご持参ください。
* Firefoxでは一部のコピー/ペースト機能が現時点では動作しないため、Chromiumベースのブラウザを推奨します。
* リモートアクセスコンソールはデフォルトでUSキーボードレイアウトを使用するため、他の国のキーボードレイアウトで特殊文字がどこに配置されているかを把握しておくか、サポートされているブラウザでコピー/ペースト機能を使用することをお勧めします。

=== OpenShift コンソールおよび Ansible Automation Platform の認証情報

OpenShift クラスターコンソールは {openshift_cluster_console_url}[こちら^] からご利用いただけます。

ログインには以下の方法があります。

* *User:* {openshift_cluster_admin_username}
* *Password:* {openshift_cluster_admin_password}

Ansible Automation Platform コンソールは {aap_controller_web_url}[こちら^] からご利用いただけます。

* *User:* {aap_controller_admin_user}
* *Password* {aap_controller_admin_password}

=== Version Information

このラボは、以下のソフトウェアバージョンを使用して開発されています。

* Red Hat OpenShift 4.18.23
* Red Hat OpenShift Virtualization 4.18.13
* Red Hat Ansible Automation Platform 2.5
* Red Hat Advanced Cluster Management for Kubernetes 2.14.0

(2025年9月18日時点の情報です)
